# np.zeros()

In [2]:
### np.zeros()

import numpy as np

In [6]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros((5, 5)).shape

(5, 5)

In [6]:
np.zeros((5, 5)).ndim

2

# np.ones()

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
a=np.ones((5,5), dtype=np.int8)
print(a, a.dtype,type(a))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] int8 <class 'numpy.ndarray'>


# np.full()

In [ ]:
# list of size 10, all filled with value 5

In [11]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [14]:
np.full(10, 5)
# np.full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [18]:
grades = np.random.randint(60, 101, 15).reshape(3, 5)
grades


array([[80, 70, 81, 87, 81],
       [60, 63, 97, 83, 74],
       [63, 86, 79, 82, 72]], dtype=int32)

In [27]:
num=np.array(np.random.randint(1,101,20)).reshape(4,5)
num2=np.arange(1,21).reshape(4,5)
num*num2
print(num)
num[[1,2],[3,4]]  # 2nd row 4th col , 3rd row 5th col

[[45 87 45 62 20]
 [31 35 13 73 97]
 [99 13 51 74 25]
 [20 56  5 87 50]]


array([73, 25], dtype=int32)

In [37]:
numbers=np.arange(1,21)
num2=numbers[0:6]
numbers[1]*=45
num2[2]=999
print(num2)
print(numbers)
num3=num2.copy()

[  1  90 999   4   5   6]
[  1  90 999   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


# np.eye(n)

it Creates Identity Matrix
np.eye(shape, start pos)
start pos it can +ve or -ve +ve foreward and -ve backward



In [27]:
np.eye(6, 6, 4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# np.empty(shape)


In [9]:
a = np.full((5,5), 0)

In [38]:
a=np.random.rand(4,4)
a

array([[0.30445636, 0.14877942, 0.47852289, 0.95891958],
       [0.30916277, 0.33586452, 0.91920822, 0.12881862],
       [0.69960638, 0.16811476, 0.72170859, 0.37807662],
       [0.57369124, 0.36441803, 0.86755556, 0.95920259]])

In [10]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# np.empty(shape)
it creates an Array and re initialize with grabage value 

In [11]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.empty((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [34]:
np.empty((5,5), dtype=int)

array([[23925768161198179, 32370111954616435, 30399722694049884,
        30962698416881756, 30962724186030185],
       [25895916907069540, 25896118771056716, 28429470870863987,
        27866439313522733, 28429415035764843],
       [28429402150535283, 31525639780892770, 33214455279779961,
        31244151918821477, 25896127360729202],
       [28429402152435824, 26740517931057270, 28429402152435824,
        27584955746091126, 30399726988689525],
       [34058953224355941, 28148004483825764, 30399731283918943,
        12948278431776879,           7929968]])

In [13]:
import time

perf_counter() is used to get high-resolution time counter.

In [19]:
start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

0.0001474999999118154


In [20]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

0.00015499999972234946


# np.random.rand(shape)

In [21]:
np.random.rand(5,5)

array([[0.39261068, 0.49457577, 0.19233899, 0.85945224, 0.93785244],
       [0.81289917, 0.90265851, 0.75451101, 0.92996149, 0.8502952 ],
       [0.22954256, 0.26470724, 0.9368351 , 0.95764554, 0.03499124],
       [0.87656491, 0.85111594, 0.60800322, 0.68782301, 0.68973966],
       [0.64561042, 0.4060215 , 0.9396424 , 0.04175117, 0.12892132]])

In [22]:
a = np.random.rand(10)*10

In [23]:
a = a.tolist()

In [24]:
a

[3.093904365385134,
 3.185669750267582,
 5.399497861592342,
 6.727035722490379,
 6.252215513588254,
 1.8384637767461254,
 4.529372961739023,
 3.417408922917071,
 5.94815467692726,
 9.374335476221438]

In [25]:
a = [int(i) for i in a]

In [26]:
a

[3, 3, 5, 6, 6, 1, 4, 3, 5, 9]

In [68]:
a

[6, 4, 7, 6, 4, 2, 4, 6, 7, 1]

In [37]:
np.random.randint(1,10)

1

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

# Answers


A 1D array of numbers from 0 to 9
```bash
arr1 = np.arange(10)
print(arr1)
```

A 3x3 matrix of all 5s
```bash
arr2 = np.full((3, 3), 5)
print(arr2)
```

A 4x4 identity matrix
```bash
arr3 = np.eye(4)
print(arr3)
```

10 evenly spaced numbers between 1 and 100
```bash
arr4 = np.linspace(1, 100, 10)
print(arr4)
```

A 2x2 array with random values between 0 and 1
```bash
arr5 = np.random.rand(2, 2)
print(arr5)
```

# numpy attributes

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
arr.shape

(2, 3)

In [41]:
arr.ndim

2

In [42]:
arr.dtype

dtype('int64')

# ndarray.itemsize

In [43]:
arr.itemsize # size in bytes of one element

8

In [ ]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

# Java
# - int --> 4 bytes
# - float --> 4 bytes
# - char --> 1 byte

In [ ]:
# import sys

# print("Size of int:", sys.getsizeof(int()))  # Integer
# print("Size of float:", sys.getsizeof(float()))  # Floating-point number
# print("Size of str:", sys.getsizeof(str()))  # String
# print("Size of list:", sys.getsizeof(list()))  # List
# print("Size of tuple:", sys.getsizeof(tuple()))  # Tuple
# print("Size of dict:", sys.getsizeof(dict()))  # Dictionary
# print("Size of set:", sys.getsizeof(set()))  # Set


Size of int: 28
Size of float: 24
Size of str: 41
Size of list: 56
Size of tuple: 40
Size of dict: 64
Size of set: 216


In [93]:
arr.nbytes # total number of bytes consumed by the array

48

In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [95]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
a = np.array([[1,2,3], [4,5,6]])

In [101]:
print(a.shape)
print(a.T.shape)

(2, 3)
(3, 2)


In [103]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [104]:
z = np.full((3,5),3)
print(z)
z = z.T
print(z)


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


# indexing and slicing

In [105]:
arr = np.array([10,20,30,40,50,60])

In [107]:
print(arr[0])
print(arr[-1])

10
60


In [111]:
print(arr[1:4])
print(arr[:3])
print(arr[0:3])

[20 30 40]
[10 20 30]
[10 20 30]


In [113]:
print(arr[::2]) # (start with 0 and step size 2)


[10 30 50]


In [44]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
print(mat[0,1])
print(mat[1])
print(mat[:,2])# Here we Acess The last column of the matrix

print(mat[:,-1])# its same : use for all row with ,-1 for last column 

2
[4 5 6]
[3 6 9]
[3 6 9]


In [ ]:
print(mat[0:2,1:])# 0:2 zero to 1 row and from 1: column onward

[[2 3]
 [5 6]]


In [46]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [47]:
arr_temp[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [123]:
# [[9, 8, 7],
# [6, 5, 4],
# [3, 2, 1]]

print(mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [51]:
arr = np.array([5, 10, 15, 20, 25])

In [52]:
arr>10

array([False, False,  True,  True,  True])

In [53]:
print(arr[arr>10]) # boolean indexing

[15 20 25]


In [54]:
indx = [0,3,4]
arr[indx]

array([ 5, 20, 25])

In [131]:
arr[0] = 50
print(arr)

[50 10 15 20 25]


# indexing with np.where()

In [132]:
arr = np.array([10, 15, 20, 25, 30])

In [133]:
idx = np.where(arr>20)
print(idx)

(array([3, 4]),)


In [134]:
print(arr[idx])

[25 30]


# array reshaping and resizing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [138]:
arr.shape

(6,)

In [139]:
reshaped = arr.reshape(2,3)

In [140]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [55]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])

In [ ]:
reshaped = arr.reshape(3,-1)# -1 means Auto calculate the number of columns

In [57]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [144]:
reshaped.shape

(3, 4)

In [154]:
a = np.array([[1, 2], [3, 4]])

In [155]:
b = a.flatten()

In [156]:
b

array([1, 2, 3, 4])

In [157]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.resize((2,3))

In [159]:
print(a)

[[1 2 3]
 [4 0 0]]


In [160]:
a = np.array([1, 2, 3, 4])

In [161]:
a.resize((2,1))

In [162]:
print(a)

[[1]
 [2]]


In [163]:
# reshape will throw error if values are insufficient
# resize will truncate or padd with zeros

In [ ]:
# 12, (4,5)--> 20 --> reshape will throw error
# 12, (4,5) --> 20 --> resize, it will pad extra element with 0

# 12-> 8--> 0

In [167]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)

(2, 3, 1)


In [166]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [58]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [60]:
a = np.array([[[1],[2],[3]], [[3],[2],[3]]])
print(a.shape)
b = np.squeeze(a)
print(b.shape)
print(b)

(2, 3, 1)
(2, 3)
[[1 2 3]
 [3 2 3]]


In [61]:
b = np.squeeze(a)
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [3 2 3]]


In [63]:
a = np.array([[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a, axis=0)
print(b.shape)
print(b)

(1, 3, 1)
(3, 1)
[[1]
 [2]
 [3]]


In [171]:
b = np.array([b])
print(b)

[[1 2 3]]


axis=0 ka matlab: pehla dimension (rows wala) → agar size 1 hai to hata do

axis=1 ka matlab: second dimension (columns wala) → agar size 1 hai to hata do

Lekin axis sirf tab hata sakte ho jab uska size 1 ho

ValueError: cannot select an axis to squeeze out which has size not equal to one
[[[1, 2, 3], [3, 2, 3]]]  we can squuze by axiix o first time but again we cant do it it will create 2 array which is not possibnle like [1,2,3] and [1,2,3]



ValueError: cannot select an axis to squeeze out which has size not equal to one


Size is the Dimensions:-(1,2,3)

In [182]:
a = np.array([
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ])

In [183]:
print(np.sum(a, axis=0)) # rows wise

[3 6 9]


In [ ]:
print(np.sum(a, axis=1)) # column wise

[6 6 6]


🔢 Suppose your array has shape (2, 3, 5):
python
Copy
Edit
import numpy as np

a = np.zeros((2, 3, 5))  # shape: (2, 3, 5)
print(a.shape)
Output:
scss
Copy
Edit
(2, 3, 5)
❓Can we squeeze along any axis?
Axis	Size	Can squeeze?
0	2	❌ No
1	3	❌ No
2	5	❌ No

👉 None of the axes have size 1 → so np.squeeze() won't do anything.

Analogy: Boxes in boxes
Imagine you have a gift box (array) with shape:

Case 1: [1, 2, 3]
➡️ 1 box with 2 smaller boxes with 3 items
You can remove the outer box (because there's only 1), and still have the same contents. ✅

So,

python
Copy
Edit
(1, 2, 3) → squeeze → (2, 3)
Case 2: [2, 2, 3]
➡️ You have 2 outer boxes — can’t just drop one of them, because each contains separate data! ❌

If you try to squeeze:

python
Copy
Edit
(2, 2, 3) → ❌ Cannot squeeze — size > 1
[[[1,2],[1,3]]]   we can squeeze in axix 0 but not 1 and its size Are 1x2x2