Numpy Math Operation


In [ ]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In Python, the + operator on lists performs concatenation, not mathematical addition.

So a + b simply joins the two lists into one.

It is equivalent to:

python
Copy
Edit
a.__add__(b)  # Also gives [1, 2, 3, 4, 5, 6]

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
a+b
# in python a+b add the element and create a list 
# but ___add___ method to do it


array([5, 7, 9])

In [9]:
print(a-b)
print(a*b)
print(a/b)
print(a>b)
ans=a>b
print(f"{type (ans[0])}-")
print(a<b)
print(a==b)
print(a|b)
print(a&b)
print(a!=b)


[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[False False False]
<class 'numpy.bool'>-
[ True  True  True]
[False False False]
[5 7 7]
[0 0 2]
[ True  True  True]


In [10]:
x=np.array([False, False, True]);
y=np.array([True, False, True]);
print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x,y))

[False False  True]
[ True False  True]
[ True  True False]


# bitwise Operator

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.bitwise_xor(a,b))
print(np.bitwise_and(a,b))



[5 7 5]
[0 0 2]
